import type { Metadata } from "next";
import { interTight } from "shared/src/theme/typography.web";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { AppProvider } from "shared/src/provider/AppProvider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import ScrollToTop from "@src/components/scroll-top/ScrollToTop";
import Script from "next/script";
import { OtplessProvider } from "@src/app/context/OtplessContext";
import { CartContextProvider } from "@src/app/context/CartContextApi";

export const metadata: Metadata = {
  title: "Fintopedia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.variable}`}>
        <AppProvider>
          <OtplessProvider>
            <CartContextProvider>
              <Navbar />
              {children}
              <ScrollToTop />
              <Footer />
            </CartContextProvider>
          </OtplessProvider>
        </AppProvider>
        <ToastContainer />
        <Script
          id="otpless-sdk"
          src="https://otpless.com/v4/headless.js"
          data-appid="8TU4ZOYC6S9Q6VMC5LLF"
          // data-appid="LKAP46LV49BNQYBVIGTE"
          strategy="beforeInteractive"
          // onLoad={() => console.log("OTPless script loaded")}
        />
      </body>
    </html>
  );
}
