import type { Metadata } from "next";
import { interTight } from "shared/src/theme/typography.web";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import BootstrapClient from "@src/components/BootstrapClient";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { AppProvider } from "shared/src/provider/AppProvider";

export const metadata: Metadata = {
  title: "Finto pedia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.variable}`}>
        <AppProvider>
          <Navbar />
          {children}
          <Footer />
        </AppProvider>
        {/* <BootstrapClient /> */}
      </body>
    </html>
  );
}
